AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with an API and lowcode lambda function

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionUri: sam/swagger.yaml
      MethodSettings:
        - ResourcePath: /{proxy+}
          HttpMethod: POST
  
  ConfigLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lowcodeLayer
      ContentUri: ./resources
      CompatibleRuntimes:
        - go1.x
      RetentionPolicy: Retain


  LowcodeFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: ./
      Handler: main
      Description: A serverless locode function integrated with a local DynamoDB
      FunctionName: lowcode-function
      Architectures:
        - x86_64
      MemorySize: 128
      Runtime: go1.x
      Timeout: 300
      Environment:
        Variables:
          DYNAMO_ENDPOINT: http://dynamodb:8000
          CONFIG_SAMPLE: /opt/sample.yaml
          AWS_REGION: us-east-1
      Layers:
        - !Ref ConfigLayer
      Events:
        ProxyEndpoint:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: 
              Ref: ApiGateway
            Auth:
              Authorizer: NONE