AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with an API and lowcode lambda function

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionUri: sam/swagger.yaml
      MethodSettings:
        - ResourcePath: /{proxy+}
          HttpMethod: POST

  LowcodeFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: app/.
      Handler: main
      Description: A serverless locode function integrated with a local DynamoDB
      FunctionName: lowcode-function
      Architectures:
        - x86_64
      MemorySize: 128
      Runtime: go1.x
      Timeout: 300
      Environment:
        Variables:
          REGION: us-east-1
          ENDPOINT: http://dynamodb:8000

      Events:
        ProxyEndpoint:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: 
              Ref: ApiGateway
            Auth:
              Authorizer: NONE