TemplateFormatVersion: 2024-01-31
Description: config sample of lowcode-lambda with go

Receiver:
  objectPathSchema: "/opt/schema.json"
  receiverType: ApiGateway
  properties:
    allowedMethods:
      - GET
      - POST
      - PUT
      # - DELETE
    allowedPath:
      - GET: "/{UserID}"
      - POST: "/"
      - PUT: "/{UserID}"
      # - DELETE: "/{UserID}"

Connector:
  objectPathSchema: "/opt/schema.json"
  connectorType: DynamoDB
  properties:
    tableName: UserTable
    keys:
      - UserID: EQ
      - EmailAddress: EQ
    filter:
      - "#Status = :Status"
    filterValues:
      - Status: true
    outputColumns:
      - UserID
      - EmailAddress
      - FirstName