version: "3.8"

networks:
  lambda-network:
    driver: bridge

services:
  lambda:
    image: raysouz/aws_lambda_provided.al2023:go1.24
    volumes:
      - ../../../go:/local/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    environment:
      - SAM_TEMPLATE=/local/workspace/aws-lowcode-lambda-go/template.yaml
    # command: ["/bin/sh", "/build.sh"]
    entrypoint: ["/bin/bash", "/sam-local.sh"]
    restart: unless-stopped
    networks:
      - lambda-network
